osx_image: xcode11
dist: trusty
sudo: false
language: node_js
node_js:
  - node
os:
  - osx
env:
  global:
    - ELECTRON_CACHE=$HOME/Library/Caches/electron
    - ELECTRON_BUILDER_CACHE=$HOME/Library/Caches/electron-builder
    - secure: UTlD9tLtvizQaXnvN+sLjccafujTtc8S325/gexlH4LOJOxwRsWUPhJbKnBhd0dlZ/FdtQsvqEKBEJBJyTgS7d9ggTPe8Qmu8hu3DT3vchq64MK9a2A6zgVocohBAjrTZ6KK1PA+SJSkEZciZVUf6R5L/q41p5NfmXgyFbqZ45P4hSxeHLzKm+LscWNHrpR5413uJhCOw73BJH1218U/KWkEu1SIc9PGAOaU4Qsx/QvWhQeGRmvBwA3xS29ArFCWOtC3epYlwgvsCnGfZhxy+4waNf4gEy6IyUvA6Q71GiOsKoCBGTj6AwLCFSjZzCjrBBUKgt5RXJJ7NnyGHiTRs5M7N5FiNnHd5j+ettsqtHzbGR+ctbtspsYjoZwH9CH3boG8Vr2C8jciqZdPqyt7G5Z4lZLGe7fo5HIHVNT51mCqHdP6zTxEV99SVBnV6xz+HqPxsQxemoGJOEvbJRGIYkrRbsP0zc5ZnYj8QEYfbEkSSWAu5Etfir65J2awq8JmzRkET4rAg5EUj2C0V9QK1v3u58ZcB7e+MfhziclNUK5g4m0tN2QxSlNFOesFLu2kSuJcdf+7E0wdPmlWHEcdgQuwHlBpJai8ipgltoN78SaLXyDh4I7vT6DSbGdAkHDfOF6N7tw0QIV3Z6wAFZjyQ/TT6rNw2pLvVi7iw+4sBH4=
    - secure: PcUaovebqO6mdP8qzRHoOKV12NYcdA/JPS/Q0CXNsP32bS52Ypeb8qePyce9MvvEKJ4O7b5b4xhOttMXi+S1b5+AEYgOiGs8NaHKX9U5DuIalbk2ChKWPV+z4XqAKrY17dnLbXYnOmXnktPmtUOYLnzVvYg6PSDYcAbViGqXOqVDIbXwpw25RUjruZzZ+V+mkHuAoOa7WooB/IPanCSU33xO31G6L8xbEkCMmrCt9+KYNovfmuqo9LFvpgvsSioYWNDDwGKwf+BIY1oBIHY3W2q+f8RIeI2pdZbrhcnpxi8RIGpqnILiGmu9nWWVkYe3x+AUZDEqMyn7fd7cevkrFl2Dp7NCiOqpGUw3JsMS/ZYvlQYQVN5kjwHinuXZ3s+Mgj9ngJpOOij3W6eY4BBl5Zs06pWL2/ZFAfJ/znyY5LOqeqUBRHKsR5df4XytYV8fdnUMAQ76+LSxEzcxmNrmWdvYst+EpfpCCnHCjVF0JxBR1AhW3q43P21rpfYTHwYLo/Tg9RTVrL9/ET5eG1Reo114NMW9cBMpMJKKYyqaI2nkgB8HB0U0wg0B+5KrMCRhdG+UAZp/PPd1vPZLmay82IpN/zko6VXI6E21MNZmrZAOkMwksRgjPhZlh+xOPnfLQzl71PyxuKBfqLbOn3I/v1wJGhQ0n5RUWVVl8ACqY80=
script:
  - yarn run check
  - "./ci-build.sh"
after_success:
  - yarn run coveralls
